services:
    nick-bestsmp:
        image: simonsecuritypedant/paperserver:1.20
        tty: true
#        command: sh
        container_name: minecraft
        networks:
          - minecraft
        restart: always
        ports:
            - 25565:25565
            - 19132:19132/udp
        volumes:
          - config:/opt/minecraft/config
          - data:/opt/minecraft/data
          - worlds:/opt/minecraft/worlds
          - logs:/opt/minecraft/logs
          - plugins:/opt/minecraft/plugins

volumes:
  config: {}
  worlds: {}
  plugins: {}
  data: {}
  logs: {}

networks:
  minecraft: {}
